name: tilepy
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - python==3.9
  - pip
  - astropy #>=4.1
  - pytz
  - scipy
  - ipython
  - numpy #>=1.19.5
  - pandas
  - pytz #==2021.1
  - healpy==1.16.2
  - pytables
  - fastparquet
  - pip:
    - gdpyc
    - MOCpy #==0.10.0
    - matplotlib #==2.2.2
    - ephem==3.7.6.0
    - ligo.skymap~=1.0.7
    - tables

